[[mgr.prepend_keymap]]
on = [ "o", "n" ]
run = 'shell --block "nvim -- %h"'
desc = "Open in Neovim"

[[mgr.prepend_keymap]]
on = [ "o", "v" ]
run = 'shell --block "code --wait -- %h"'
desc = "Open in VSCode"

[[mgr.prepend_keymap]]
on = [ "o", "t" ]
run = 'shell --orphan -- if [ -d "%h" ]; then target="%h"; else target="$(dirname -- "%h")"; fi; ya emit cd -- "$target"; ya emit quit'
desc = "Open in Terminal"
